### ISSUE TITLE
Delay transitions or scroll before animations begin?

### ISSUE THREAD

**Issue by dougkeeling** [gmrchk/swup#33]
Hi there, I absolutely love Swup!  Very easy to use, and everything seems to work great right out of the box.

The only thing I'm noticing is that the transitions I'm creating with CSS can look a little odd when used in conjunction with the page scroll.  I've tried using the `doScrollingRightAway: true` setting assuming it would scroll, then start the animations, but it seems like the page loads so fast that it doesn't really change anything. 

So, the question is: Is there a way to scroll to the top, then start all the animations?

I've also noticed that, even when not scrolling, occasionally the "out" transitions don't seem to have enough time to complete before the page loads.  (I've got the cache disabled as well, because certain parts of the site are dynamic — not sure if that contributes to the issue or not.)  

Thanks!

**Comment by dougkeeling** [comment]
I see that my bottom comments about the "out transitions" were addressed by you in issue #11 .  It might not hurt to make a note about that in the documentation. Your example of using multiple classes on one item was helpful. Thanks!

**Comment by gmrchk** [comment]
Hi, glad you like it and thanks for checking the solved issues.

`doScrollingRightAway` option determines whether swup waits for the page to animate **OUT** or not to start the scroll, but will still continue with the **IN** animation in any way. swup doesn't have the option to *animate out > scroll > animate in* simply for the reason of being a bad approach, as you probably don't want a user to wait longer than needed. After all, the content of the next page is why user clicked the link.

Your best option would be to set `animateScroll: false`, so you animate the page out, jump to the top without the animation, and animate in. Of course, that assumes that your contents are hidden and no elements would be jumping around. Another option is to change the animation to look different or make it more optimized if that's the issue you are facing.
