### ISSUE TITLE
Manually update window.location when ajax request fails

### ISSUE THREAD

**Issue by dylanfisher** [gmrchk/swup#37]
Would you be open to adding an option or changing the default behavior of how Swup interacts with broken links (404, 500, etc.)? If I click on a link that results in a XHR error, Swup doesn't follow the link. I'd expect Swup to fall back to normal browser behavior, where clicking on a 404 link leads to a 404 page. 

Would it be possible to set `window.location` to the new URL in cases where the XHR request fails?

**Comment by gmrchk** [comment]
I have been looking into this some time ago, but totally forgot about that, as you usually don't have that many 404/500 on brand new sites. Good job spotting this.

I will look into it in a next few days. In a meanwhile, how about this proposed behavior?

**500** - fallback to normal browser view (reload...).
**404** - check if the structure has all the necessary elements that would be replaced (`#swup` by default) and do all the animating magic as swup normally does. If any elements are missing - reload.

**Comment by dylanfisher** [comment]
That sounds great. Let me know if I can help in any way.

**Comment by gmrchk** [comment]
Fixed in 1.1.0. swup now also fallbacks to normal page visit in case the page structure doesn't fit (not just for server error). 

I suddenly remembered why I didn't finish implementing this the last time. There is a bit of unexpected behavior... or maybe I just don't get it... anyway, just to keep the record here:

Browsers seem to remember that you visited the page using pushState, and that no request is needed. This is a bit of a problem because swup does the pushState before any animations begin (to make Safari and mobile browsers create a screenshot when the page hasn't been animated out yet). At that time we simply can't tell if the request will go through. That means reloading the browser (`history.reload()`) on error doesn't work because browser won't load the page when you go back.

The only option is to go back in history and make browser navigate to the same page again with `window.location = "..."`. However, it seems that browsers handle history changing asynchronously and that it takes some time, so the navigation needs to be handled in the popstate handler. `skipPopStateHandling` option turned out to be very handy for this. 

Thank you for your input @dylanfisher. Shoutout to @cirmaciu for his help when I was dead stuck.

**Comment by andrispraulitis** [comment]
Hi @gmrchk, how can we handle 302 redirects?

Example would be I go to /page2 (but there is a problem that needs to be fixed on /page1), then redirect happens and swup loads /page1, however browser url bar still shows /page2 so once problem fixed impossible now to go to a /page2 as swup says it's a same page because url now updated and can't navigate.

**Comment by lukepass** [comment]
I experienced the same problem as @andrispraulitis and it's quite evident with forms. Thanks!

**Comment by daun** [comment]
It should be possible to detect 301 and 302 redirects by [comparing the request url and the response url](https://stackoverflow.com/a/35570850). Not sure about browser support, but it would be an improvement either way.
